### ISSUE TITLE
Porting of translations

### ISSUE THREAD

**Issue by bosd** [OCA/e-commerce#532]
Should the translations automatically ported between versions?
(By the transbot or weblate?

Noticed that some translations are'nt ported to newer branches.
For example:
https://github.com/OCA/e-commerce/tree/13.0/website_sale_attribute_filter_price/i18n
Contains Dutch, Spanish Catalan.

The 14 branch contains no translations.
https://github.com/OCA/e-commerce/tree/14.0/website_sale_attribute_filter_price/i18n

**Comment by pedrobaeza** [comment]
When the modules is migrated, everything is catched, but if translations are done after the migration PR, no automatic forward-port can't be done due to technical reasons. Weblate has anyway a translation memory for proposing the sentences for translating things.

**Comment by bosd** [comment]
Thanks! unitl now,I'd never got an translation proposal on weblate. Even for comon phrases used in evy view like "Last modified on". Is that something one needs to activate?

**Comment by pedrobaeza** [comment]
Not AFAIK, but @sbidoul is the most knowledgeable on Weblate.

**Comment by francesco-ooops** [comment]
@pedrobaeza and @sbidoul , I also consider the lack of porting of translations to be a **significant** waste of resources/workhours for translators and of content / quality of content for OCA. 

Personally, I've translated to Italian 1550 strings for 12.0 in the last 18 months on OCA weblate, and when we'll migrate our customers to a newer version I know I will need to re-translate most of them, since:

- most likely portings to newer versions have been done before translations were added to older version

- if translation is added to 12.0 but module is being ported from 13.0 to 14.0, the translation for 12.0 is ignored (correct me if I’m wrong on this); 

But even if I were to translate again the modules, it wouldn't be a quick or a clean job for three reasons: 

- first of all, how can I check which of the OCA modules with a complete Italian translation in 12.0 are not translated in the version we're migrating to?

- since translation suggestions are not cross-project for versions (eg: between helpdesk-12.0 and helpdesk-13.0) my best bet to transfer the translation is... a manual copy-paste?

- If the new translations were to be done manually, most probably there would be quite a few fields changing names from one version to another, and that would be confusing for the user.

Plus another issue which I’ve noticed affects quality and consistency: 

Even very common strings such as "last modified on", “cancel” and "display name" often need to be translated from scratch (I think I translated these strings at least 100 times each), due to the fact that translation suggestions are not cross-project at all (eg: between helpdesk-12.0 and stock-logistics-warehouse-12.0). So for projects where there are very little translations in your language, you can’t access suggestions for the most common strings.

This leads to the risk of inconsistencies as everyone with little odoo experience who doesn't know what’s the “standard” translation in that language for the string can translate it slightly differently (and the “unofficial” translation can even end up in the suggested translations for that project).

When the user ends up using an ERP where the same field is named slightly different in three different models, I don’t think that’s great UX.

I think what would be necessary is to implement either: 

- a procedure to update empty strings using translations for the same module in older projects (if there’s a perfect match on the string, of course) going back a few version - maybe marking them as “needs revision”?

- a procedure to retain the highest number of translated strings when porting modules, going back a few versions

- a better system to suggest translations that have been used most commonly in a language, either in the same project/repo or in other projects/repos

**Comment by pedrobaeza** [comment]
We are restricted to the possibilities that Weblate platform offers. The translation memory, as commented, is there as support and for me it has been enough for maintaining Spanish across several versions in OCA modules. If you know any possible method for doing what you say, it's welcome and indeed everything can be improved.

**Comment by francesco-ooops** [comment]
> We are restricted to the possibilities that Weblate platform offers. The translation memory, as commented, is there as support and for me it has been enough for maintaining Spanish across several versions in OCA modules. If you know any possible method for doing what you say, it's welcome and indeed everything can be improved.

I don't have a solution but I will investigate with my devs and with weblate if possibile

if we could also have an input from those in OCA who take care of the weblate/translation part, that would be great :)

**Comment by francesco-ooops** [comment]
> We are restricted to the possibilities that Weblate platform offers.

The technical implementation is above my skills, but I can see how some Weblate features like 

[shared translation memory](https://docs.weblate.org/en/latest/admin/memory.html#shared-translation-memory)

[glossary](https://docs.weblate.org/en/latest/user/glossary.html#glossary) and [glossary checks](https://docs.weblate.org/en/latest/user/glossary.html#glossary)

[automatic translation](https://docs.weblate.org/en/latest/user/translating.html#automatic-translation)

are not used or under-used on OCA Weblate. Implementing even just one of these tools could improve consistency, translation speed, maintenance and availability of translations. Is there any plan for using any of these tools @sbidoul ?

Eg. instead of translating strings like "Company" each time ending up with 10 different translations for the same string (eg: [Sale Order in es](https://translation.odoo-community.org/search/?page=2&limit=100&q=+source%3A%3D%22Sale+Order%22+language%3Aes&sort_by=-priority%2Cposition)), users could focus on more uncommon translation strings, and make sure they are not lost when the module is ported to a new version

**Comment by pedrobaeza** [comment]
AFAIK, shared translation memory is activated.

**Comment by sbidoul** [comment]
I'm convinced we could take advantage of more weblate features, yes. For instance, the fact there is one project per addon and branch is not optimal. Back then we could not immediately find a solution but there might be a better approach.

What is lacking is resources to do the investigation and necessary configuration, deployment, integration.
I will personally not have time to work on any sizeable weblate evolution project in the mid/medium term.
Anyone willing to dive into the topic and drive the project to conclusion is most welcome, and I'm willing to help with onboarding and any guidance that would be necessary.

**Comment by francesco-ooops** [comment]
> AFAIK, shared translation memory is activated.

do you have any example of translation memory shared among all (or more than one) projects? 

Because if it's just some setting, then I'd really like to know how to turn it on :)

@sbidoul thanks for the reply, hopefully some resources will come forward, especially now that a new branch will be created with all the porting issues described above

**Comment by pedrobaeza** [comment]
@francesco-ooops resources don't appear magically. If you want to handle this, you can onboard on this task, and the rest of the community will be thankful to you.

**Comment by francesco-ooops** [comment]
> @francesco-ooops resources don't appear magically. If you want to handle this, you can onboard on this task, and the rest of the community will be thankful to you.

I'm aware of that, I'm checking what we can do internally :)

**Comment by pedrobaeza** [comment]
Great, let us know.
