### ISSUE TITLE
[BUG] website_sale_checkout_skip_payment not compatible with delivery methods

### ISSUE THREAD

**Issue by vdewulf** [OCA/e-commerce#741]
## Module
website_sale_checkout_skip_payment
Tested on version 12 Community Edition

## Describe the bug
When buying product from eCommerce, I select a delivery method available (not the first one). On the Sale Order in backend, the wrong delivery method is selected. It's always the first one in the list of delivery methods configuration that is selected on the SO.

## To Reproduce
**Affected versions**: version 12

1. Install website_sale_checkout_skip_payment and website_delivery. 
2. Configure the customer partner so that the payment screen will be skipped
3. Configure 2 delivery methods and publish them
4. Go on eCommerce and buy a product. Select the second delivery method.
5. Validate 
6. Go on SO in backend and check the delivery method: wrong method is selected.

**Expected behavior**
6. The delivery method chosen by the customer on the eCommerce is selected o
![Delivery Methods - Odoo](https://user-images.githubusercontent.com/27895270/215143974-70e92be9-ee2f-4812-b693-fe7582cea92d.png)
n the SO on the backend
![SO002 - wrong delivery method in backend - Odoo](https://user-images.githubusercontent.com/27895270/215143943-f16378c3-f7fc-414a-a13b-47f71cb38695.png)
![Administrator_customer_config_skip - Odoo](https://user-images.githubusercontent.com/27895270/215143951-9a09475f-6eba-47cc-bf0a-a816a9c47e11.png)
![Payment My Website_Delivery](https://user-images.githubusercontent.com/27895270/215143964-da818489-e930-4c20-b181-1fece0aff319.png)

**Comment by victor-champonnois** [comment]
The issue happens at the last step 
![image](https://user-images.githubusercontent.com/92781722/218125046-38715c17-7415-4463-947c-c80354361cda.png)
Here, when changing the delivery method, the method ` _update_website_sale_delivery` should be triggered by [this JS code](https://github.com/odoo/odoo/blob/c53081f10befd4f1c98e46a450ed3bc71a6246ed/addons/website_sale_delivery/static/src/js/website_sale_delivery.js#L59).

But when the customer is allowed to skip_payment, the JS code throws an error at this line :


```
Uncaught TypeError: 
``$pay_button.data(...) is undefined
_onCarrierClick http://localhost:8012/web/content/985-5287018/1/web.assets_frontend.js:295
```

[at this line](https://github.com/odoo/odoo/blob/c53081f10befd4f1c98e46a450ed3bc71a6246ed/addons/website_sale_delivery/static/src/js/website_sale_delivery.js#L59)

so the method is not tiggered, the carrier is not updated, and the first one on the list is used.

I think this might be because the payment route is skipped and we go directly to the confirmation route (like below). 

https://github.com/OCA/e-commerce/blob/d049af51695c7ebb1bf7f86ce125949a41f7f9ec/website_sale_checkout_skip_payment/views/website_sale_template.xml#L14-L18

However I don't have a clearer idea.
@sergio-teruel Do you know a way to fix this issue ?

**Comment by sergio-teruel** [comment]
Sorry @victor-champonnois The website_sale_checkout_skip_payment module has not include any JS code, so I think that this error is related to other module...

**Comment by chienandalu** [comment]
@sergio-teruel I took a look and it seems to be related to the absence of the payment button element. https://github.com/odoo/odoo/blob/c53081f10befd4f1c98e46a450ed3bc71a6246ed/addons/website_sale_delivery/static/src/js/website_sale_delivery.js#L12

Anyway, I couldn't reproduce the bug in the versions we're currently supporting for our customers (>13).

So @victor-champonnois feel free to propose a PR patching de issue for 12.0
